// src/components/inputBox/InputBox.jsx
import React, { useRef } from "react";
import PropTypes from "prop-types";
import "./inputBox.less";

function InputBox({ addTask }) {
  const inputRef = useRef();
  const handleKeyPress = (e) => {
    if (e.key.toUpperCase() === "ENTER") {
      const inputVal = inputRef.current.value;
      addTask(inputVal);
      inputRef.current.value = "";
    }
  };
  return (
    <div className="input-box-wrapper">
      <input
        className="input"
        ref={inputRef}
        type="text"
        placeholder="添加任务"
        onKeyPress={handleKeyPress}
      />
    </div>
  );
}

InputBox.propTypes = {
  addTask: PropTypes.func,
};

export default InputBox;

// src/components/InputBox.vue
<template>
  <div class="input-box-wrapper">
    <input
      class="input"
      v-model="inputVal"
      placeholder="添加任务"
      @keypress="handleKeyPress"
    />
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  setup(props, context) {
    const inputVal = ref("");

    const handleKeyPress = (e) => {
      if (e.key.toUpperCase() === "ENTER") {
        context.emit("addTask", inputVal.value);
        inputVal.value = "";
      }
    };

    return {
      inputVal,
      handleKeyPress,
    };
  },
};
</script>

<style lang="less" scoped>
.input-box-wrapper {
  margin-bottom: 24px;

  .input {
    box-sizing: border-box;
    width: 500px;
    height: 36px;
    padding: 0 12px;
    border: 2px solid #e5e5e5;
    border-radius: 2px;
    font-size: 16px;
    outline: none;

    &::placeholder {
      color: #999;
    }
  }
}
</style>
