// src/components/task/Task.jsx
import React, { Component } from "react";
import PropTypes from "prop-types";

class Task extends Component {
  render() {
    const { taskList } = this.props;
    return (
      <div className="task-wrapper">
        {taskList.map((item) => (
          <TaskItem
            key={item.id}
            info={item}
            completeTask={this.props.completeTask}
            deleteTask={this.props.deleteTask}
          />
        ))}
      </div>
    );
  }
}

class TaskItem extends Component {
  render() {
    const { info, completeTask, deleteTask } = this.props;
    const { id, task, taskStatus } = info;
    return (
      <div className="task-item-wrapper">
        <div className="check-box" onClick={() => completeTask(id)}>
          {taskStatus === "uncompleted" ? "待完成" : "已完成"}
        </div>
        <div className="task-content">{task}</div>
        <div className="delete-btn" onClick={() => deleteTask(id)}>
          删除
        </div>
      </div>
    );
  }
}

Task.propTypes = {
  taskList: PropTypes.array,
  completeTask: PropTypes.func,
  deleteTask: PropTypes.func,
};

TaskItem.propTypes = {
  info: PropTypes.object,
  completeTask: PropTypes.func,
  deleteTask: PropTypes.func,
};

export default Task;

// src/components/Task.vue
<template>
  <div class="task-wrapper">
    <task-item
      v-for="item in taskList"
      :key="item.id"
      :info="item"
      @completeTask="completeTask"
      @deleteTask="deleteTask"
    />
  </div>
</template>

<script>
import TaskItem from "./TaskItem.vue";
export default {
  components: {
    TaskItem,
  },
  props: {
    taskList: {
      type: Array,
      default: () => [],
    },
  },
  setup(props, context) {
    const completeTask = (val) => {
      context.emit("completeTask", val);
    };

    const deleteTask = (val) => {
      context.emit("deleteTask", val);
    };

    return {
      completeTask,
      deleteTask,
    };
  },
};
</script>

<style lang="less" scoped>
.task-wrapper {
  width: 500px;
  overflow: hidden;
}
</style>
