// src/components/todoApp/TodoApp.jsx
import React, { useState } from "react";
import { uuid, formatCurrentDate } from "../../utils/index";
import InputBox from "../inputBox/InputBox";
import Task from "../task/Task";
import "./todoApp.less";

function TodoApp() {
  const [taskList, setTaskList] = useState([]);
  const addTask = (val) => {
    const newTask = {
      id: uuid(),
      createDate: formatCurrentDate("YYYY-MM-DD HH:mm:ss"),
      task: val,
      taskStatus: "uncomplete",
    };
    setTaskList([...taskList, newTask]);
  };
  const completeTask = (id) => {
    const targetIndex = taskList.findIndex((item) => item.id === id);
    const target = taskList[targetIndex];
    taskList.splice(targetIndex, 1, {
      ...target,
      taskStatus:
        target.taskStatus === "uncomplete" ? "complete" : "uncomplete",
    });
    // setTaskList要传入新的taskList值
    setTaskList([...taskList]);
  };
  const deleteTask = (id) => {
    const targetIndex = taskList.findIndex((item) => item.id === id);
    taskList.splice(targetIndex, 1);
    // setTaskList要传入新的taskList值
    setTaskList([...taskList]);
  };
  return (
    <div className="todo-app-wrapper">
      <header className="title">TODO</header>
      <InputBox addTask={addTask} />
      <Task
        list={taskList}
        completeTask={completeTask}
        deleteTask={deleteTask}
      />
    </div>
  );
}

export default TodoApp;

// src/components/TodoApp.vue
<template>
  <div class="todo-app-wrapper">
    <header class="title">TODO</header>
    <input-box @addTask="addTask"></input-box>
    <task
      :taskList="taskList"
      @completeTask="completeTask"
      @deleteTask="deleteTask"
    />
  </div>
</template>

<script>
import { createUuid, formatCurrentDate } from "../utils/index";
import InputBox from "./InputBox.vue";
import Task from "./Task.vue";
import { ref } from "vue";
export default {
  components: {
    InputBox,
    Task,
  },
  setup() {
    const taskList = ref([]);

    const addTask = (val) => {
      taskList.value.push({
        id: createUuid(),
        createDate: formatCurrentDate(),
        task: val,
        taskStatus: "uncomplete",
      });
    };

    const completeTask = (val) => {
      const targetIndex = taskList.value.findIndex((i) => i.id === val);
      const target = taskList.value[targetIndex];
      if (targetIndex > -1) {
        taskList.value.splice(targetIndex, 1, {
          ...target,
          taskStatus:
            target.taskStatus === "uncomplete" ? "completed" : "uncomplete",
        });
      }
    };

    const deleteTask = (val) => {
      const targetIndex = taskList.value.findIndex((i) => i.id === val);
      if (targetIndex > -1) {
        taskList.value.splice(targetIndex, 1);
      }
    };

    return {
      taskList,
      addTask,
      completeTask,
      deleteTask,
    };
  },
};
</script>

<style lang="less" scoped>
.todo-app-wrapper {
  width: 500px;
  margin: 40px auto;

  .title {
    margin-bottom: 16px;
    font-size: 40px;
    text-align: center;
  }
}
</style>
