// src/components/TodoApp.jsx
import React, { Component } from "react";
import InputBox from "./inputBox/InputBox";
import Task from "./task/Task";

class TodoApp extends Component {
  constructor(props) {
    super(props);
    this.state = {
      taskList: [],
    };
    this.addTask = this.addTask.bind(this);
    this.completeTask = this.completeTask.bind(this);
    this.deleteTask = this.deleteTask.bind(this);
  }
  addTask(value) {
    const newTask = {
      id: new Date(),
      createTime: "",
      task: value,
      taskStatus: "uncompleted",
    };
    const taskList = [...this.state.taskList, newTask];
    this.setState({
      taskList,
    });
  }
  completeTask(id) {
    const { taskList } = this.state;
    const targetIndex = taskList.findIndex((item) => item.id === id);
    const target = taskList[targetIndex];
    taskList.splice(targetIndex, 1, {
      ...target,
      taskStatus: "completed",
    });
    this.setState({
      taskList,
    });
  }
  deleteTask(id) {
    const { taskList } = this.state;
    const targetIndex = taskList.find((item) => item.id === id);
    taskList.splice(targetIndex, 1);
    this.setState({
      taskList,
    });
  }
  render() {
    return (
      <div className="todo-app-wrapper">
        <InputBox addTask={this.addTask} />
        <Task
          taskList={this.state.taskList}
          completeTask={this.completeTask}
          deleteTask={this.deleteTask}
        />
      </div>
    );
  }
}

export default TodoApp;

// src/components/TodoApp.vue
<template>
  <div class="todo-app-wrapper">
    <header class="title">TODO</header>
    <input-box @addTask="addTask"></input-box>
    <task
      :taskList="taskList"
      @completeTask="completeTask"
      @deleteTask="deleteTask"
    />
  </div>
</template>

<script>
import { createUuid, formatCurrentDate } from "../utils/index";
import InputBox from "./InputBox.vue";
import Task from "./Task.vue";
import { ref } from "vue";
export default {
  components: {
    InputBox,
    Task,
  },
  setup() {
    const taskList = ref([]);

    const addTask = (val) => {
      taskList.value.push({
        id: createUuid(),
        createDate: formatCurrentDate(),
        task: val,
        taskStatus: "uncomplete",
      });
    };

    const completeTask = (val) => {
      const targetIndex = taskList.value.findIndex((i) => i.id === val);
      const target = taskList.value[targetIndex];
      if (targetIndex > -1) {
        taskList.value.splice(targetIndex, 1, {
          ...target,
          taskStatus:
            target.taskStatus === "uncomplete" ? "completed" : "uncomplete",
        });
      }
    };

    const deleteTask = (val) => {
      const targetIndex = taskList.value.findIndex((i) => i.id === val);
      if (targetIndex > -1) {
        taskList.value.splice(targetIndex, 1);
      }
    };

    return {
      taskList,
      addTask,
      completeTask,
      deleteTask,
    };
  },
};
</script>

<style lang="less" scoped>
.todo-app-wrapper {
  width: 500px;
  margin: 40px auto;

  .title {
    margin-bottom: 16px;
    font-size: 40px;
    text-align: center;
  }
}
</style>
